from deconstruct_lc import tools_lc
from deconstruct_lc.scores.norm_score import NormScore

def main():
    k = 6
    lce = 1.6
    lca = 'SGEQAPDTNKR'
    sup35 = "MSDSNQGNNQQNYQQYSQNGNQQQGNNRYQGYQAYNAQAQPAGGYYQNYQGYSGYQQGGY" \
            "QQYNPDAGYQQQYNPQGGYQQYNPQGGYQQQFNPQGGRGNYKNFNYNNNLQGYQAGFQPQ" \
            "SQGMSLNDFQKQQKQAAPKPKKTLKLVSSSGIKLANATKKVGTKPAESDKKEEEKSAETK" \
            "EPTKEPTKVEEPVKKEEKPVQTEEKTEEKSELPKVEDLKISESTHNTNNANVTSADALIK" \
            "EQEEEVDDEVVNDMFGGKDHVSLIFMGHVDAGKSTMGGNLLYLTGSVDKRTIEKYEREAK" \
            "DAGRQGWYLSWVMDTNKEERNDGKTIEVGKAYFETEKRRYTILDAPGHKMYVSEMIGGAS" \
            "QADVGVLVISARKGEYETGFERGGQTREHALLAKTQGVNKMVVVVNKMDDPTVNWSKERY" \
            "DQCVSNVSNFLRAIGYNIKTDVVFMPVSGYSGANLKDHVDPKECPWYTGPTLLEYLDTMN" \
            "HVDRHINAPFMLPIAAKMKDLGTIVEGKIESGHIKKGQSTLLMPNKTAVEIQNIYNETEN" \
            "EVDMAMCGEQVKLRIKGVEEEDISPGFVLTSPKNPIKSVTKFVAQIAIVELKSIIAAGFS" \
            "CVMHVHTAIEEVHIVKLLHKLEKGTNRKSKKPPAFAKKGMKVIAVLETEAPVCVETYQDY" \
            "PQLGRFTLRDQGTTIAIGKIVKIAE"
    #print(sup35[253])
    ns = tools_lc.display_lc(sup35[253], k, lca, lce)
    #print(ns)
    motifs = tools_lc.count_lc_motifs(sup35[253], k, lca, lce)
    #print(motifs)
    norm = NormScore()
    #print(norm.lc_norm_score([sup35[253]]))
    ns = tools_lc.display_lc(sup35[253], k, lca, lce)
    #print(ns)

    pab1 = 'MADITDKTAEQLENLNIQDDQKQAATGSESQSVENSSASLYVGDLEPSVSEAHLYDIFSP' \
           'IGSVSSIRVCRDAITKTSLGYAYVNFNDHEAGRKAIEQLNYTPIKGRLCRIMWSQRDPSL' \
           'RKKGSGNIFIKNLHPDIDNKALYDTFSVFGDILSSKIATDENGKSKGFGFVHFEEEGAAK' \
           'EAIDALNGMLLNGQEIYVAPHLSRKERDSQLEETKAHYTNLYVKNINSETTDEQFQELFA' \
           'KFGPIVSASLEKDADGKLKGFGFVNYEKHEDAVKAVEALNDSELNGEKLYVGRAQKKNER' \
           'MHVLKKQYEAYRLEKMAKYQGVNLFVKNLDDSVDDEKLEEEFAPYGTITSAKVMRTENGK' \
           'SKGFGFVCFSTPEEATKAITEKNQQIVAGKPLYVAIAQRKDVRRSQLAQQIQARNQMRYQ' \
           'QATAAAAAAAAGMPGQFMPPMFYGVMPPRGVPFNGPNPQQMNPMGGMPKNGMPPQFRNGP' \
           'VYGVPPQGGFPRNANDNNQFYQQKQRQALGEQLYKKVSAKTSNEEAAGKITGMILDLPPQ' \
           'EVFPLLESDELFEQHYKEASAAYESFKKEQEQQTEQA'
    print(len(pab1))
    wop = pab1[0:300]
    #print(wop)
    #print(wop)
    motifs = tools_lc.count_lc_motifs(wop, k, lca, lce)
    #print(motifs)
    norm = NormScore()
    print(norm.lc_norm_score([wop]))
    ns = tools_lc.display_lc(pab1, k, lca, lce)
    #print(ns)
    nck = 'MAEEVVVVAKFDYVAQQEQELDIKKNERLWLLDDSKSWWRVRNSMNKTGFVPSNYVERKN' \
          'SARKASIVKNLKDTLGIGKVKRKPSVPDSASPADDSFVDPGERLYDLNMPAYVKFNYMAE' \
          'REDELSLIKGTKVIVMEKCSDGWWRGSYNGQVGWFPSNYVTEEGDSPLGDHVGSLSEKLA' \
          'AVVNNLNTGQVLHVVQALYPFSSSNDEELNFEKGDVMDVIEKPENDPEWWKCRKINGMVG' \
          'LVPKNYVTVMQNNPLTSGLEPSPPQCDYIRPSLTGKFAGNPWYYGKVTRHQAEMALNERG' \
          'HEGDFLIRDSESSPNDFSVSLKAQGKNKHFKVQLKETVYCIGQRKFSTMEELVEHYKKAP' \
          'IFTSEQGEKLYLVKHLS'
    #norm = NormScore([nck])
    #print(norm.lc_norm_score())
    nwasp = 'MSSVQQQPPPPRRVTNVGSLLLTPQENESLFTFLGKKCVTMSSAVVQLYAADRNCMWSKK' \
            'CSGVACLVKDNPQRSYFLRIFDIKDGKLLWEQELYNNFVYNSPRGYFHTFAGDTCQVALN' \
            'FANEEEAKKFRKAVTDLLGRRQRKSEKRRDPPNGPNLPMATVDIKNPEITTNRFYGPQVN' \
            'NISHTKEKKKGKAKKKRLTKADIGTPSNFQHIGHVGWDPNTGFDLNNLDPELKNLFDMCG' \
            'ISEAQLKDRETSKVIYDFIEKTGGVEAVKNELRRQAPPPPPPSRGGPPPPPPPPHNSGPP' \
            'PPPARGRGAPPPPPSRAPTAAPPPPPPSRPSVAVPPPPPNRMYPPPPPALPSSAPSGPPP' \
            'PPPSVLGVGPVAPPPPPPPPPPPGPPPPPGLPSDGDHQVPTTAGNKAALLDQIREGAQLK' \
            'KVEQNSRPVSCSGRDALLDQIRQGIQLKSVADGQESTPPTPAPTSGIVGALMEVMQKRSK' \
            'AIHSSDEDEDEDDEEDFEDDDEWED'
    #norm = NormScore([nwasp])
    #print(norm.lc_norm_score())
    nephrin = 'MALGTTLRASLLLLGLLTEGLAQLAIPASVPRGFWALPENLTVVEGASVELRCGVSTPGS' \
              'AVQWAKDGLLLGPDPRIPGFPRYRLEGDPARGEFHLHIEACDLSDDAEYECQVGRSEMGP' \
              'ELVSPRVILSILVPPKLLLLTPEAGTMVTWVAGQEYVVNCVSGDAKPAPDITILLSGQTI' \
              'SDISANVNEGSQQKLFTVEATARVTPRSSDNRQLLVCEASSPALEAPIKASFTVNVLFPP' \
              'GPPVIEWPGLDEGHVRAGQSLELPCVARGGNPLATLQWLKNGQPVSTAWGTEHTQAVARS' \
              'VLVMTVRPEDHGAQLSCEAHNSVSAGTQEHGITLQVTFPPSAIIILGSASQTENKNVTLS' \
              'CVSKSSRPRVLLRWWLGWRQLLPMEETVMDGLHGGHISMSNLTFLARREDNGLTLTCEAF' \
              'SEAFTKETFKKSLILNVKYPAQKLWIEGPPEGQKLRAGTRVRLVCLAIGGNPEPSLMWYK' \
              'DSRTVTESRLPQESRRVHLGSVEKSGSTFSRELVLVTGPSDNQAKFTCKAGQLSASTQLA' \
              'VQFPPTNVTILANASALRPGDALNLTCVSVSSNPPVNLSWDKEGERLEGVAAPPRRAPFK' \
              'GSAAARSVLLQVSSRDHGQRVTCRAHSAELRETVSSFYRLNVLYRPEFLGEQVLVVTAVE' \
              'QGEALLPVSVSANPAPEAFNWTFRGYRLSPAGGPRHRILSSGALHLWNVTRADDGLYQLH' \
              'CQNSEGTAEARLRLDVHYAPTIRALQDPTEVNVGGSVDIVCTVDANPILPGMFNWERLGE' \
              'DEEDQSLDDMEKISRGPTGRLRIHHAKLAQAGAYQCIVDNGVAPPARRLLRLVVRFAPQV' \
              'EHPTPLTKVAAAGDSTSSATLHCRARGVPNIVFTWTKNGVPLDLQDPRYTEHTYHQGGVH' \
              'SSLLTIANVSAAQDYALFTCTATNALGSDQTNIQLVSISRPDPPSGLKVVSLTPHSVGLE' \
              'WKPGFDGGLPQRFCIRYEALGTPGFHYVDVVPPQATTFTLTGLQPSTRYRVWLLASNALG' \
              'DSGLADKGTQLPITTPGLHQPSGEPEDQLPTEPPSGPSGLPLLPVLFALGGLLLLSNASC' \
              'VGGVLWQRRLRRLAEGISEKTEAGSEEDRVRNEYEESQWTGERDTQSSTVSTTEAEPYYR' \
              'SLRDFSPQLPPTQEEVSYSRGFTGEDEDMAFPGHLYDEVERTYPPSGAWGPLYDEVQMGP' \
              'WDLHWPEDTYQDPRGIYDQVAGDLDTLEPDSLPFELRGHLV'
    # nicd = nephrin[1077:1242]
    # norm = NormScore([nicd])
    # print(norm.lc_norm_score())
    # print(nicd)
    # ns = tools_lc.display_lc(nicd, k, lca, lce)
    # print(ns)
    # motifs = tools_lc.count_lc_motifs(nicd, k, lca, lce)
    # print(motifs)
    # gfp = 'MSKGEELFTGVVPILVELDGDVNGHKFSVSGEGEGDATYGKLTLKFICTTGKLPVPWPTL' \
    #       'VTTFSYGVQCFSRYPDHMKQHDFFKSAMPEGYVQERTIFFKDDGNYKTRAEVKFEGDTLV' \
    #       'NRIELKGIDFKEDGNILGHKLEYNYNSHNVYIMADKQKNGIKVNFKIRHNIEDGSVQLAD' \
    #       'HYQQNTPIGDGPVLLPDNHYLSTQSALSKDPNEKRDHMVLLEFVTAAGITHGMDELYK'
    # #ns = tools_lc.display_lc(nicd+gfp, k, lca, lce)
    # #norm = NormScore([nicd+gfp])
    # #print(norm.lc_norm_score())
    # #print(ns)
    fus = 'MASNDYTQQATQSYGAYPTQPGQGYSQQSSQPYGQQSYSGYSQSTDTSGYGQSSYSSYGQ' \
          'SQNTGYGTQSTPQGYGSTGGYGSSQSSQSSYGQQSSYPGYGQQPAPSSTSGSYGSSSQSS' \
          'SYGQPQSGSYSQQPSYGGQQQSYGQQQSYNPPQGYGQQNQY'

    fus = 'MASNDYTQQATQSYGAYPTQPGQGYSQQSSQPYGQQSYSGYSQSTDTSGYGQSSYSSYGQ' \
          'SQNTGYGTQSTPQGYGSTGGYGSSQSSQSSYGQQSSYPGYGQQPAPSSTSGSYGSSSQSS' \
          'SYGQPQSGSYSQQPSYGGQQQSYGQQQSYNPPQGYGQQNQYNSSSGGGGGGGGGGNYGQD' \
          'QSSMSSGGGSGGGYGNQDQSGGGGSGGYGQQDRGGRGRGGSGGGGGGGGGGYNRSSGGYE' \
          'PRGRGGGRGGRGGMGGSDRGGFNKFGGPRDQGSRHDSEQDNSDNNTIFVQGLGENVTIES' \
          'VADYFKQIGIIKTNKKTGQPMINLYTDRETGKLKGEATVSFDDPPSAKAAIDWFDGKEFS' \
          'GNPIKVSFATRRADFNRGGGNGRGGRGRGGPMGRGGYGGGGSGGGGRGGFPSGGGGGGGQ' \
          'QRAGDWKCPNPTCENMNFSWRNECNQCKAPKPDGPGGGPGGSHMGGNYGDDRRGGRGGYD' \
          'RGGYRGRGGDRGGFRGGRGGGDRGGFGPGKMDSRGEHRQDRRERPY'
    ns = tools_lc.display_lc(fus[0:214], k, lca, lce)
    #print(fus[0:214])
    #print(ns)
    # print(fus)
    norm = NormScore()
    #print(norm.lc_norm_score([fus]))
    pex5 = 'MDVGSCSVGNNPLAQLHKHTQQNKSLQFNQKNNGRLNESPLQGTNKPGISEAFISNVNAI' \
           'SQENMANMQRFINGEPLIDDKRRMEIGPSSGRLPPFSNVHSLQTSANPTQIKGVNDISHW' \
           'SQEFQGSNSIQNRNADTGNSEKAWQRGSTTASSRFQYPNTMMNNYAYASMNSLSGSRLQS' \
           'PAFMNQQQSGRSKEGVNEQEQQPWTDQFEKLEKEVSENLDINDEIEKEENVSEVEQNKPE' \
           'TVEKEEGVYGDQYQSDFQEVWDSIHKDAEEVLPSELVNDDLNLGEDYLKYLGGRVNGNIE' \
           'YAFQSNNEYFNNPNAYKIGCLLMENGAKLSEAALAFEAAVKEKPDHVDAWLRLGLVQTQN' \
           'EKELNGISALEECLKLDPKNLEAMKTLAISYINEGYDMSAFTMLDKWAETKYPEIWSRIK' \
           'QQDDKFQKEKGFTHIDMNAHITKQFLQLANNLSTIDPEIQLCLGLLFYTKDDFDKTIDCF' \
           'ESALRVNPNDELMWNRLGASLANSNRSEEAIQAYHRALQLKPSFVRARYNLAVSSMNIGC' \
           'FKEAAGYLLSVLSMHEVNTNNKKGDVGSLLNTYNDTVIETLKRVFIAMNRDDLLQEVKPG' \
           'MDLKRFKGEFSF'
    norm = NormScore()
    #print(len(pex5))
    #print(norm.lc_norm_score([pex5[0:300]]))
    #print(pex5)
    ns = tools_lc.display_lc(pex5,  k, lca, lce)
    #print(ns)
    pex13 = 'MSSTAVPRPKPWETSASLEEPQRNAQSLSAMMTSNQQDSRPTEESNNSNSASESAPEVLP' \
            'RPAALNSSGTYGESNTIPGIYGNSNYGIPYDNNPYSMNSIYGNSIGRYGYGGSYYGNNYG' \
            'SFYGGGYGAGAGYGMNNGSGLGESTKATFQLIESLIGAVTGFAQMLESTYMATHNSFFTM' \
            'ISVAEQFGNLKEMLGSFFGIFAIMKFLKKILYRATKGRLGIPPKNFAESEGSKNKLIEDF' \
            'QKFNDSGTINSNEKATRRKISWKPLLFFLMAVFGFPYLLNKFITKLQTSGTIRASQGNGS' \
            'EPIDPSKLEFARALYDFVPENPEMEVALKKGDLMAILSKKDPLGRDSDWWKVRTKNGNIG' \
            'YIPYNYIEIIKRRKKIEHVDDETRTH'
    #print(norm.lc_norm_score([pex13]))
    pex14 = 'MSDVVSKDRKALFDSAVSFLKDESIKDAPLLKKIEFLKSKGLTEKEIEIAMKEPKKDGIV' \
            'GDEVSKKIGSTENRASQDMYLYEAMPPTLPHRDWKDYFVMATATAGLLYGAYEVTRRYVI' \
            'PNILPEAKSKLEGDKKEIDDQFSKIDTVLNAIEAEQAEFRKKESETLKELSDTIAELKQA' \
            'LVQTTRSREKIEDEFRIVKLEVVNMQNTIDKFVSDNDGMQELNNIQKEMESLKSLMNNRM' \
            'ESGNAQDNRLFSISPNGIPGIDTIPSASEILAKMGMQEESDKEKENGSDANKDDNAVPAW' \
            'KKAREQTIDSNASIPEWQKNTAANEISVPDWQNGQVEDSIP'
    #print(norm.lc_norm_score([pex14]))



if __name__ == '__main__':
    main()